### ISSUE TITLE
Camel build error

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/camel-atlasmap#1]
Unable to create skeleton for camel-atlasmap due to camel build error w/ 2.19.0-SNAPSHOT

> [ERROR] Failed to execute goal org.apache.camel:camel-package-maven-plugin:2.19.0-SNAPSHOT:prepare-components (prepare) on project camel-atlasmap: Error loading dataformat model from camel-core. Reason: java.io.FileNotFoundException: /Users/mattrpav/.m2/repository/org/apache/camel/camel-core/2.19.0-SNAPSHOT/camel-core-2.19.0-SNAPSHOT.jar/org/apache/camel/model/dataformat/atlasmap.json (Not a directory) -> [Help 1]

**Comment by davsclaus** [comment]
Logged a ticket
https://issues.apache.org/jira/browse/CAMEL-11049

**Comment by mattrpav** [comment]
Note: Per Claus build a ProducerComponent for now

**Comment by mattrpav** [comment]
* Built a Producer-only Component 
 * Do not inherit from Camel parent pom at this time
