### ISSUE TITLE
Update camel-atlasmap to use 1.16.0 or newer version

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/camel-atlasmap#9]
camel-atlasmap needs to be updated to use a more recent version

**Comment by rhuss** [comment]
I tried to update but it seems that the API changed and the method for creating  context with a given mapping has vanished: https://github.com/atlasmap/camel-atlasmap/blob/master/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java#L185

@mattrpav : Is there any easy workaround this or is now only possible to create the context with an URI or an File ?

**Comment by rhuss** [comment]
I see the following steps to do:

* Extend AtlasMappingService to work with JSON (in addition to JAXB) --> https://github.com/atlasmap/atlasmap/issues/146
* Extend AtlasContextFactory to take an AltasMapping in its createContext() method
* Change every reference from com.mediadriver to io.atlasmap (but there can be changes in other names, too). This also affects the test.

So we need a new version of atlasmap/atlasmap, too (1.18)

**Comment by igarashitm** [comment]
merged
